---
title: "04_ES22_MAGs_MT_analysis"
output: html_document
date: "2024-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library("tidyverse")
library("DESeq2")
library("pheatmap")
library("vsn")
library("apeglm")
library("paletteer")
```

```{r dataload}
setwd("XXXX")
dat <- read.table("ES_samples_vs_ES22_IMP_min75_max10_breadth_05_all_read_counts_coverm_no_missmatch_filtering.tsv_cut", sep = "\t", row.names=1, header=T)  ### Raw counts per gene in MAGs
b6 <-  read.csv("ES22_IMP_min75_max10_breadth_05_all.genes.faa-vs-FunTaxDB1.3.b6", sep = "\t", header = F) ### Functional annotation of Genes
meta <- read.table("All_samples_meta.tsv", row.names=1, sep = "\t", header = T) ### Meta information for samples
scaff2bin <- read.table("ES22_IMP_S_MAGs_GrowDB_scaff2bin.tsv", sep = "\t") %>% dplyr::rename(scaffold = V1)%>% dplyr::rename(bin = V2) %>%
    mutate(bin = ifelse(!startsWith(bin, "ES22"), paste0("GrowDB_", bin), bin)) ### Matching contigs to MAGs

dat_stress <- dat %>% 
  rownames_to_column("gene") %>% 
  gather("sample", "coverage", -gene) %>% 
  left_join(meta %>% rownames_to_column("sample")) %>% 
  filter(phase == "stress")%>% 
  select(sample,coverage,gene) %>% 
  spread("sample", "coverage") %>% 
  column_to_rownames("gene")

meta_stress <- meta %>% 
filter(phase == "stress") %>%
  mutate(temperature = str_replace(temperature, "normal", "background"))


dat_recovery <- dat %>% 
  rownames_to_column("gene") %>% 
  gather("sample", "coverage", -gene) %>% 
  left_join(meta %>% rownames_to_column("sample")) %>% 
  filter(phase == "recovery")%>% 
  select(sample,coverage,gene) %>% 
  spread("sample", "coverage") %>% 
  column_to_rownames("gene")

meta_recovery <- meta %>% 
filter(phase == "recovery") %>%
  mutate(temperature = str_replace(temperature, "normal", "background"))
```

```{r dds_stress}
smallestGroupSize <- 3


dds_stress <- DESeqDataSetFromMatrix(countData = dat_stress,
                              colData = meta_stress,
                              design= ~  velocity * salinity * temperature)

keep_stress <- rowSums(counts(dds_stress) >= 5) >= smallestGroupSize
dds_stress <- dds_stress[keep_stress,]


dds_stress <- DESeq(dds_stress)
res_stress <- results(dds_stress, contrast=c("temperature","increased","background"))
resOrdered_stress <- res_stress[order(res_stress$pvalue),]
summary(res_stress)
sum(res_stress$padj < 0.1, na.rm=TRUE)
resultsNames(dds_stress)


res_stress_velocity <- results(dds_stress, contrast=c("velocity","reduced","normal"),alpha = 0.05)
resLFC_velocity_stress <- lfcShrink(dds_stress, coef="velocity_reduced_vs_normal", type="apeglm",res = res_stress_velocity) 
resLFC_velocity_stress%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>%  filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_salinity <- results(dds_stress, contrast=c("salinity","salt","background"),alpha = 0.05)
resLFC_salinity_stress <- lfcShrink(dds_stress, coef="salinity_salt_vs_background", type="apeglm",res = res_stress_salinity) 
resLFC_salinity_stress%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_temp <- results(dds_stress, contrast=c("temperature","increased","background"),alpha = 0.05)
resLFC_temp_stress <- lfcShrink(dds_stress, coef="temperature_increased_vs_background",res = res_stress_temp, type="apeglm") 
resLFC_temp_stress%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_velocity_salinity <- results(dds_stress, name=c("velocityreduced.salinitysalt"),alpha = 0.05)
lfcShrink(dds_stress, coef="velocityreduced.salinitysalt", type="apeglm",res = res_stress_velocity_salinity) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_velocity_temperature <- results(dds_stress, name=c("velocityreduced.temperatureincreased"),alpha = 0.05)
lfcShrink(dds_stress, coef="velocityreduced.temperatureincreased", type="apeglm",res = res_stress_velocity_temperature) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>%filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_salt_temperature <- results(dds_stress, name=c("salinitysalt.temperatureincreased"),alpha = 0.05)
lfcShrink(dds_stress, coef="salinitysalt.temperatureincreased", type="apeglm",res = res_stress_salt_temperature) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_stress_all_stressors <- results(dds_stress, name=c("velocityreduced.salinitysalt.temperatureincreased"),alpha = 0.05)
resLFC_all_stress_stress <- lfcShrink(dds_stress, coef="velocityreduced.salinitysalt.temperatureincreased", type="apeglm",res = res_stress_all_stressors) 
resLFC_all_stress_stress%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)
```

```{r dds_recovery}
smallestGroupSize <- 3


dds_recovery <- DESeqDataSetFromMatrix(countData = dat_recovery,
                              colData = meta_recovery,
                              design= ~  velocity * salinity * temperature)

keep_recovery <- rowSums(counts(dds_recovery) >= 5) >= smallestGroupSize
dds_recovery <- dds_recovery[keep_recovery,]


dds_recovery <- DESeq(dds_recovery)


res_recovery_velocity <- results(dds_recovery, contrast=c("velocity","reduced","normal"),alpha = 0.05)
resLFC_velocity_recovery <- lfcShrink(dds_recovery, coef="velocity_reduced_vs_normal", type="apeglm",res = res_recovery_velocity) 
resLFC_velocity_recovery%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>%  filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_salinity <- results(dds_recovery, contrast=c("salinity","salt","background"),alpha = 0.05)
resLFC_salinity_recovery <- lfcShrink(dds_recovery, coef="salinity_salt_vs_background", type="apeglm",res = res_recovery_salinity) 
resLFC_salinity_recovery%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_temp <- results(dds_recovery, contrast=c("temperature","increased","background"),alpha = 0.05)
resLFC_temp_recovery <- lfcShrink(dds_recovery, coef="temperature_increased_vs_background",res = res_recovery_temp, type="apeglm") 
resLFC_temp_recovery%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_velocity_salinity <- results(dds_recovery, name=c("velocityreduced.salinitysalt"),alpha = 0.05)
lfcShrink(dds_recovery, coef="velocityreduced.salinitysalt", type="apeglm",res = res_recovery_velocity_salinity) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_velocity_temperature <- results(dds_recovery, name=c("velocityreduced.temperatureincreased"),alpha = 0.05)
lfcShrink(dds_recovery, coef="velocityreduced.temperatureincreased", type="apeglm",res = res_recovery_velocity_temperature) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>%filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_salt_temperature <- results(dds_recovery, name=c("salinitysalt.temperatureincreased"),alpha = 0.05)
lfcShrink(dds_recovery, coef="salinitysalt.temperatureincreased", type="apeglm",res = res_recovery_salt_temperature) %>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

res_recovery_all_stressors <- results(dds_recovery, name=c("velocityreduced.salinitysalt.temperatureincreased"),alpha = 0.05)
resLFC_all_stress_recovery <- lfcShrink(dds_recovery, coef="velocityreduced.salinitysalt.temperatureincreased", type="apeglm",res = res_recovery_all_stressors) 
resLFC_all_stress_recovery%>%  as.data.frame()  %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin) %>% filter(abs(log2FoldChange) > 1 & padj < 0.05)

```



```{r ggplot2_temp_stress}
alpha <- 0.05
library(ggrepel)

res_taxa_added_temp_stress <- as.data.frame(resLFC_temp_stress) %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1))%>% 
        mutate(V9 = str_replace(V9, "^\\S* ", ""))

res_taxa_added_bin_info_temp_stress <- res_taxa_added_temp_stress %>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin)
res_taxa_added_bin_info_temp_stress$V9 <- str_extract(res_taxa_added_bin_info_temp_stress$V9, ".*(?=n=)")

significant_points_temp_stress <- res_taxa_added_bin_info_temp_stress %>%
  filter(abs(log2FoldChange) > 1 & padj < alpha)

volcano_plot_temp_stress <- ggplot(res_taxa_added_bin_info_temp_stress, aes(x = log2FoldChange, y = -log10(padj))) + ## For Figure Supplementary
  geom_point(data = filter(res_taxa_added_bin_info_temp_stress, abs(log2FoldChange) > 1 & padj < alpha),
             aes(color = bin),
             size = 3, shape = 20, key_glyph = "point") +
   scale_color_manual(values = c("#CDA54EFF", "#AD4951FF"),"MAG")+
  geom_point(data = filter(res_taxa_added_bin_info_temp_stress, !(abs(log2FoldChange) > 1 & padj < alpha)),
             color = "gray", # Color for non-significant points
             size = 3, shape = 20) +
  geom_hline(yintercept = -log10(alpha), linetype = "dashed", color = "brown") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "brown") +
  geom_vline(xintercept = 0, color = "black") +
  labs(title = "Temperature increase",
       x = "Effect size: log2(fold-change)",
       y = "-log10(adjusted p-value)") +
  theme_bw()+
  geom_text_repel(data = filter(res_taxa_added_bin_info_temp_stress, abs(log2FoldChange) > 1 & padj < alpha),
                   aes(x = log2FoldChange, y = -log10(padj), label = V9),
                    size = 3,
                    box.padding = 0.5,
                    point.padding = 0.5,
                    force = 2,
                    max.overlaps = Inf) 

```
```{r ggplot2_velocity_stress}
alpha <- 0.05
library(ggrepel)

res_taxa_added_velocity_stress <- as.data.frame(resLFC_velocity_stress) %>% rownames_to_column("gene") %>% left_join(b6  %>% select(V1,V9) %>% dplyr::rename(gene =V1)) %>% 
        mutate(V9 = str_replace(V9, "^\\S* ", "")) %>% 
  mutate(V9 = str_replace(V9, "chaperonin", "Chaperonin"))

res_taxa_added_bin_info_velocity_stress <- res_taxa_added_velocity_stress %>% mutate(scaffold = gsub('_[^_]*$', '', gene)) %>% left_join(scaff2bin)
res_taxa_added_bin_info_velocity_stress$V9 <- str_extract(res_taxa_added_bin_info_velocity_stress$V9, ".*(?=n=)")

significant_points_velocity_stress <- res_taxa_added_bin_info_velocity_stress %>%
  filter(abs(log2FoldChange) > 1 & padj < alpha) %>%
  group_by(bin) %>%
  mutate(bin_count = n())



volcano_plot_velocity_stress <-  ggplot(res_taxa_added_bin_info_velocity_stress, aes(x = log2FoldChange, y = -log10(padj))) +
    geom_point(data = significant_points_velocity_stress,
               aes(color = ifelse(bin_count >1, bin,  " MAGs with only one significant gene"),shape = ifelse(V9 == "Chaperonin GroEL ", "triangle", "circle")),
               size = 3.5)+
    scale_color_paletteer_d("cartography::multi.pal", "MAG",direction=1,dynamic=T)+
    scale_shape(labels=c("no","yes"))+
    geom_point(data = filter(res_taxa_added_bin_info_velocity_stress, !(abs(log2FoldChange) > 1 & padj < alpha)),
               color = "gray", # Color for non-significant points
               size = 3.5, shape = 20) +
    geom_hline(yintercept = -log10(alpha), linetype = "dashed", color = "brown") +
    geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "brown") +
    geom_vline(xintercept = 0, color = "black") +
    labs(title = "Flow velocity after stressor phase",
         x = "Effect size: log2(fold-change)",
         y = "-log10(adjusted p-value)",
         shape = "Annotated as Chaperonin GroEL") +
    theme_bw()+
    geom_text_repel(data = filter(res_taxa_added_bin_info_velocity_stress, abs(log2FoldChange) > 1 & padj < alpha),
                    aes(x = log2FoldChange, y = -log10(padj), label = ifelse(V9 == "Chaperonin GroEL ", "", V9)),
                    size = 3,
                    box.padding = 0.5,
                    point.padding = 0.5,
                    force = 2,
                    max.overlaps = Inf) + 
  guides(shape = guide_legend( 
    override.aes=list(color = "grey")))+xlim(0,3.5)+ ylim(1,3.75)

volcano_plot_velocity_stress_presentation <- ggplot(res_taxa_added_bin_info_velocity_stress, aes(x = log2FoldChange, y = -log10(padj))) +
    geom_point(data = significant_points_velocity_stress,
               aes(color = ifelse(bin_count >1, bin,  " MAGs with only one significant gene"),shape = ifelse(str_detect(V9,"(?i)chaperon"), "triangle", "circle")),
               size = 5)+
    scale_color_paletteer_d("cartography::multi.pal", "MAG",direction=1,dynamic=T)+
    scale_shape(labels=c("no","yes"))+
    geom_point(data = filter(res_taxa_added_bin_info_velocity_stress, !(abs(log2FoldChange) > 1 & padj < alpha)),
               color = "gray", # Color for non-significant points
               size = 5, shape = 20) +
    geom_hline(yintercept = -log10(alpha), linetype = "dashed", color = "brown") +
    geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "brown") +
    geom_vline(xintercept = 0, color = "black") +
    labs(title = "Flow velocity after stressor phase",
         x = "Effect size: log2(fold-change)",
         y = "-log10(adjusted p-value)",
         shape = "Annotated as chaperone") +
    theme_bw()+
    geom_text_repel(data = filter(res_taxa_added_bin_info_velocity_stress, abs(log2FoldChange) > 1 & padj < alpha),
                    aes(x = log2FoldChange, y = -log10(padj), label= ifelse(grepl("chaperon", V9, ignore.case = TRUE), "", V9)),
                    size = 5,
                    box.padding = 0.5,
                    point.padding = 0.5,
                    force = 2,
                    max.overlaps = Inf) + 
    guides(shape = guide_legend( 
        override.aes=list(color = "grey")))+xlim(0,3.5)+ ylim(1,3.75)
volcano_plot_velocity_stress_presentation
ggsave("ES22_IMP_MAG_DE_velocity_stress_presentation.jpeg", width = 15, height = 10) ### For Figure

```
